// Slide data for PresentationDeck
export const slides = [
  {
    id: 1,
    layout: 'title',
    title: 'Customer Ordering System (COS)',
    subtitle: 'CSE323 Software Engineering — Final Presentation',
    meta: 'Team Dev-Cosmic · Members A, B, C, D · 2026-05-18',
  },
  {
    id: 2,
    layout: 'two-col',
    title: 'Agenda',
    left: ['1. Problem & Scope', '2. Architecture — Vertical Slicing', '3. Tech Stack — React / FastAPI', '4. Frontend — 4-Zone Routing', '5. Backend — FastAPI Vertical Slices', '6. Security Middleware'],
    right: ['7. Requirements & Design (Phases 1–2)', '8. Testing — The 70/20/10 Pyramid', '9. Verification vs Validation', '10. Agile Sprint Journey', '11. Honest Status & Q&A'],
  },
  {
    id: 3,
    layout: 'bullets',
    title: '1. Problem & Scope',
    bullets: [
      { label: 'What:', text: 'A customer ordering system for a 25-product hardware catalog.' },
      { label: 'Flow:', text: 'Storefront browse → Cart → Checkout → Payment → Admin fulfillment.' },
      { label: 'Zones:', text: 'Storefront | Checkout | User Account | Admin Panel' },
    ],
  },
  {
    id: 4,
    layout: 'two-col-table',
    title: '2. Architecture — Vertical Slicing',
    bullets: [
      'Rejected: Horizontal slicing — high communication overhead, "chain vulnerability".',
      'Adopted: Vertical slicing — each member owns a full-stack business sub-problem.',
      'Human = Orchestrator (defines interfaces & API contracts).',
      'AI = Labor (generates internal logic within bounded constraints).',
    ],
    table: {
      headers: ['Member', 'Slice'],
      rows: [['A', 'Checkout, Cart, Catalog'], ['B', 'Payment'], ['C', 'Tickets / Support'], ['D', 'Auth, Orders, Inventory']],
    },
  },
  {
    id: 5,
    layout: 'bullets',
    title: '2b. The Polyglot Pivot',
    bullets: [
      { text: 'Started as a Node.js / Express prototype.' },
      { text: 'Pivoted canonical backend to Python / FastAPI on port 8000.' },
      { text: 'Why safe: JWT (HS256) is language-agnostic — React frontend and either backend interoperate on the same token contract.' },
      { text: 'Vertical slicing permits per-slice runtime choices without breaking the system.' },
    ],
  },
  {
    id: 6,
    layout: 'three-cards',
    title: '3. Tech Stack',
    cards: [
      { heading: 'Frontend', items: ['React 18 + Vite', 'Tailwind CSS', 'Framer Motion', '"Dev-Cosmic" liquid-glassmorphism UI library'] },
      { heading: 'Backend (Canonical)', items: ['FastAPI (Python 3.11+)', 'SQLAlchemy ORM + SQLite', 'Bcrypt hashing + HS256 JWT', 'APScheduler (stale-order sweep)'] },
      { heading: 'DevOps / QA', items: ['Pytest (backend)', 'Playwright POM (E2E)', 'GitHub Actions CI'] },
    ],
  },
  {
    id: 7,
    layout: 'four-cards',
    title: '4. Frontend — 4-Zone Routing',
    cards: [
      { heading: '1. Public Storefront', text: 'Catalog browsing, product discovery, Hero CTA.', color: '#00BFFF' },
      { heading: '2. Checkout Funnel', text: 'Session cart, shipping details, promo codes.', color: '#22C55E' },
      { heading: '3. User Account', text: 'Authenticated order history & settings.', color: '#7C3AED' },
      { heading: '4. Admin Panel', text: 'Role-gated fulfillment & inventory control.', color: '#EF4444' },
    ],
    footer: 'Orchestrated via react-router-dom. All elements use the shared UI library.',
  },
  {
    id: 8,
    layout: 'two-col-table',
    title: '5. Backend — FastAPI Vertical Slices',
    bullets: [
      'Routers: auth, orders, inventory, cart, catalog, payment, events.',
      'Services layer holds business logic; routers stay thin.',
      'Global exception handling: services raise DomainError; single handler converts to JSON.',
      'Persistence: SQLAlchemy models, SQLite; fresh in-memory DB per test.',
    ],
    table: {
      headers: ['Endpoint', 'Auth', 'Purpose'],
      rows: [
        ['POST /auth/login', 'public', 'Issue Bearer JWT'],
        ['GET /orders', 'admin', 'Paginated list, filter'],
        ['PATCH /orders/{id}', 'admin', 'Guarded transition matrix'],
        ['GET /inventory', 'admin', 'Products with low_stock'],
      ],
    },
  },
  {
    id: 9,
    layout: 'two-col',
    title: '6. Security Middleware — Semantic Perimeter',
    left: ['Prompt-Injection Guard (app/middleware/security.py)', 'Pure-ASGI middleware; buffers and replays the request body.', 'Scans POST/PUT/PATCH bodies for instruction-override / jailbreak patterns.', 'Match → HTTP 400 PROMPT_INJECTION_BLOCKED.'],
    right: ['PII Redaction Firewall', 'RedactionFilter attached to root + uvicorn loggers.', 'Masks emails, card numbers, and sensitive key/values (password, cvv, token).', 'Secrets never reach the terminal or log files.'],
  },
  {
    id: 10,
    layout: 'two-col',
    title: '7. Requirements & Design (Phases 1–2)',
    left: ['Phase 1 — Requirements', 'Actor classification (Primary / Supporting / Offstage).', 'AI-as-Malicious-User edge-case discovery — ≥5 negative cases per persona.', 'Traceability heatmaps map every requirement to a test case (zero orphans).'],
    right: ['Phase 2 — Design', 'System Sequence Diagrams (SSDs).', 'UML Activity Diagrams with explicit code decision points.', 'Gherkin scenarios (Given/When/Then) per user story.', 'API contracts locked before implementation.'],
  },
  {
    id: 11,
    layout: 'audit',
    title: '7b. QA — The Ambiguity Audit',
    transforms: [
      { from: '"fast"', to: '"< 500 ms response"' },
      { from: '"secure"', to: '"JWT-validated, Bcrypt-hashed"' },
    ],
    note: 'AI acted as Senior QA to strip subjective terms. Recorded in docs/requirements/QA_AUDIT_LOG.md.',
  },
  {
    id: 12,
    layout: 'table-only',
    title: '8. Testing — The 70/20/10 Pyramid',
    table: {
      headers: ['Layer', 'Share', 'Tooling'],
      rows: [
        ['Unit', '~70%', 'Pytest — pure logic, validators, transition matrix'],
        ['Integration', '~20%', 'Pytest + httpx — router + service + DB'],
        ['E2E', '~10%', 'Playwright POM — real browser'],
      ],
    },
    bullets: ['e2e marker isolates browser specs for separate CI jobs.'],
  },
  {
    id: 13,
    layout: 'two-col',
    title: '9. Verification vs Validation',
    left: ['Verification', '"Are we building the product right?"', '→ Unit + Integration tests (Pytest).'],
    right: ['Validation', '"Are we building the right product?"', '→ UAT via Playwright POM against Gherkin acceptance scenarios.'],
  },
  {
    id: 14,
    layout: 'timeline',
    title: '10. Agile Sprint Journey',
    items: [
      { sprint: 'Sprint 0', text: 'Architectural skeleton, vertical-slicing mandate, Git rules.' },
      { sprint: 'Sprint 1', text: 'First end-to-end cart → API → DB loop.' },
      { sprint: 'Sprint 2', text: 'Phase 1/2 documentation, SSDs, prompt library.' },
      { sprint: 'Sprint 3', text: 'The polyglot pivot to FastAPI; UI library lockdown.' },
      { sprint: 'Sprint 4', text: 'System convergence, Playwright suites, rubric validation.', highlight: true },
    ],
  },
  {
    id: 15,
    layout: 'ai-workflow',
    title: '10b. AI-Native Workflow',
    heading: 'Test-Driven Prompting (TDP)',
    subtitle: 'A failing test must precede implementation.',
    left: { role: 'Human', action: 'Orchestrates' },
    right: { role: 'AI', action: 'Generates bounded logic' },
  },
  {
    id: 16,
    layout: 'two-col',
    title: '11. Honest Status',
    left: ['✅ Complete', 'All four vertical slices implemented and routed.', 'Security middleware (prompt-injection guard + PII redaction).', 'Phase 1–2 docs, QA Audit Log, Test Pyramid Report, V&V Statement.', 'Traceability heatmaps for all four members.'],
    right: ['⏳ Open Items (Disclosed)', 'Per-member agile logbooks for Phases 2–4 (Members A/B/C) — to be authored manually.', 'A live-server smoke test of the new security middleware.'],
  },
  {
    id: 17,
    layout: 'title',
    title: 'Thank You',
    subtitle: 'Questions?',
    meta: 'docs/requirements/FINAL_DELIVERABLES.md · http://localhost:8000/docs',
  },
];
